FROM golang:1.12-alpine as builder
RUN apk add --no-cache git
RUN adduser -D -u 10001 appuser
ADD . /go
RUN go get -d -v
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o rt-app .

FROM scratch
COPY --from=builder /go/rt-app /rt-app
COPY --from=builder /etc/passwd /etc/passwd
USER appuser
EXPOSE 8080
CMD ["/rt-app"]
